### ISSUE TITLE
CSS could be more efficient.

### ISSUE THREAD

**Issue by AbleLincoln** [da-gyata/prj-rev-bwfs-dasmoto#6]
Do you see how you've written the same font-family, font-size, font-weight, and color three separate times? You could write all of these styles at once, like so:
```css
.brushes, #frames, .paint {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/da-gyata/prj-rev-bwfs-dasmoto/blob/master/DasmotoProject/resources/CSS/das.css#L14-L36
